DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                            VARCHAR(255)                            NOT NULL,
    email                           VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_users             PRIMARY KEY (id),
    CONSTRAINT UQ_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                            VARCHAR(255),
    description                     VARCHAR(1023),
    available                       BOOLEAN,
    owner_id                        BIGINT,
    request_id                      BIGINT,
    CONSTRAINT pk_item              PRIMARY KEY (id),
    CONSTRAINT fk_item_users        FOREIGN KEY (owner_id)      REFERENCES users (id)   ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date                      TIMESTAMP WITHOUT TIME ZONE,
    end_date                        TIMESTAMP WITHOUT TIME ZONE,
    item_id                         BIGINT,
    user_id                         BIGINT,
    status                          VARCHAR(31),
    CONSTRAINT pk_booking           PRIMARY KEY (id),
    CONSTRAINT fk_booking_item      FOREIGN KEY (item_id)       REFERENCES items (id)   ON DELETE CASCADE,
    CONSTRAINT fk_booking_users     FOREIGN KEY (user_id)       REFERENCES users (id)   ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description                     VARCHAR(512),
    user_id                         BIGINT,
    created                         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_requests          PRIMARY KEY (id),
    CONSTRAINT fk_requests_users    FOREIGN KEY (user_id)       REFERENCES users (id)   ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comment (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text                            VARCHAR(1023)                           NOT NULL,
    item_id                         BIGINT                                  NOT NULL,
    user_id                         BIGINT                                  NOT NULL,
    created                         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment           PRIMARY KEY (id),
    CONSTRAINT fk_comment_users     FOREIGN KEY (user_id)       REFERENCES users (id)   ON DELETE CASCADE,
    CONSTRAINT fk_comment_item      FOREIGN KEY (item_id)       REFERENCES items (id)   ON DELETE CASCADE
);