DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(512) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255),
    description     VARCHAR(512),
    available       BOOLEAN,
    owner_id        BIGINT REFERENCES users (id),
    request_id      BIGINT
);

CREATE TABLE IF NOT EXISTS bookings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date      TIMESTAMP WITHOUT TIME ZONE,
    end_date        TIMESTAMP WITHOUT TIME ZONE,
    item_id         BIGINT REFERENCES items (id),
    user_id         BIGINT REFERENCES users (id),
    status          VARCHAR(25)
);

CREATE TABLE IF NOT EXISTS comments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text            VARCHAR(512),
    item_id         BIGINT REFERENCES items (id),
    user_id         BIGINT REFERENCES users (id),
    created         TIMESTAMP WITHOUT TIME ZONE
);